# Generated by Django 5.1.5 on 2025-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutleryFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='EdibleItem',
        ),
    ]
