# Generated by Django 5.2 on 2025-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible', '0003_alter_cutleryfactory_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutleryfactory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
