# Generated by Django 5.2 on 2025-04-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edible', '0004_cutleryfactory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutleryfactory',
            options={'verbose_name': 'Cutlery Factory', 'verbose_name_plural': 'Cutlery Factories'},
        ),
    ]
